### ISSUE TITLE
 Button on elegant UI

### ISSUE THREAD

**Issue by sergeysova** [atomixinteractions/ui#1]
Рефакторить `@atomix-ui/button`

Нужна красивая кнопочка в Elegant UI стиле. Это минимальные градиенты, цветные тени и приятные цвета. Накидаю несколько примеров.

![image](https://user-images.githubusercontent.com/5620073/33204345-4a0a3c28-d114-11e7-9f6e-e98ea9ee2692.png)
https://dribbble.com/shots/3722008-Elegant-UI-kit-Users-Screen/attachments/835004

![image](https://user-images.githubusercontent.com/5620073/33204412-7e4eeb14-d114-11e7-86d7-7d84694a6a4a.png)
![image](https://user-images.githubusercontent.com/5620073/33204416-8202deb4-d114-11e7-9744-02400ac07a9d.png)
![image](https://user-images.githubusercontent.com/5620073/33204422-8797bdcc-d114-11e7-9e91-040c97372eda.png)

![image](https://user-images.githubusercontent.com/5620073/33204436-96622b4e-d114-11e7-92b1-2fd442e2e5ae.png)

![image](https://user-images.githubusercontent.com/5620073/33204462-a9d7e2f4-d114-11e7-93a9-521a271fbf32.png)

Идея в легкости и воздушности.

**Comment by userbq201** [comment]
что делать с такого типа тенью
`box-shadow: 0 0 3px 13px rgba(246, 57, 122, 0.1);`
хардкорно ?
